name: CI

on: [push]

jobs:
  Build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Build
      run: echo Build Complete..

  Test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Test
      run: echo Test Completed..


  Deploy:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Deploy
      run: echo Deploy Completed..